// export * from '../utils/language/locales';
// export * from './home';
// export * from './news';
// export * from './contactUs';
// // export * from './kenya';
// export * from './navigator';
// export * from './region';
// export * from './aboutUs';
// export * from './download';
// export * from './agreement';
// export * from './solarPanel';
// export * from './parts';
// export * from './production';
// export * from './version';
// export * from './kenyaNavigator';
